# Generated by Django 4.1.9 on 2023-08-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='date',
            new_name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='media',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='state',
        ),
        migrations.AddField(
            model_name='media',
            name='conversion_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to='converted_media/'),
        ),
        migrations.AddField(
            model_name='media',
            name='original_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
