# Generated by Django 4.1.9 on 2023-08-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_date_media_conversion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
    ]
