# Generated by Django 4.1.9 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
